### ISSUE TITLE
Webpack: Module build failed, Typescript emitted no output

### ISSUE THREAD

**Issue by vvnsk** [quilljs/parchment#58]
Hello,

I'm trying to use Quill Editor in Aurelia and Webpack, which has parchment as a dependency.

The build is successful with transpileOnly as true, but due to which i lose the Typescript capabilities. When i donot defin ethe transpileOnly for ts-loader,

```
{
         test: /\.ts?$/,
         use: [
                "babel-loader",
                {
                       loader: "ts-loader",
                }
        ]
},
```

I get the following Error,

```
ERROR in ./node_modules/parchment/src/attributor/attributor.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\attributor\attributor.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 10:0-49 30:15-25
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/attributor/class.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\attributor\class.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 11:0-49 31:11-26
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/attributor/store.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\attributor\store.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 13:0-49 33:11-26
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/attributor/style.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\attributor\style.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 12:0-49 32:11-26
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/abstract/container.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\abstract\container.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 2:0-54 21:13-26
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/abstract/format.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\abstract\format.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 3:0-48 22:10-20
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/abstract/leaf.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\abstract\leaf.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 4:0-44 23:8-16
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/block.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\block.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 7:0-37 26:9-18
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/embed.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\embed.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 8:0-37 24:9-18
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/inline.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\inline.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 6:0-39 27:10-20
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/scroll.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\scroll.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 5:0-39 25:10-20
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/blot/text.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\blot\text.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 9:0-35 28:8-16
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper

ERROR in ./node_modules/parchment/src/registry.ts
Module build failed: Error: Typescript emitted no output for C:\Users\project\node_modules\parchment\src\registry.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (C:\Users\project\node_modules\ts-loader\dist\index.js:39:15)
    at Object.loader (C:\Users\project\node_modules\ts-loader\dist\index.js:21:12)
 @ ./node_modules/parchment/src/parchment.ts 14:0-39 16:9-23 17:10-25 18:8-21 19:9-23 20:12-29
 @ ./node_modules/quill/core.js
 @ ./node_modules/quill/quill.js
 @ ./src/resources/custom-elements/quill-editor/quill-editor.ts
 @ ./src/resources/index.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:3333 @babel/polyfill aurelia-bootstrapper
```

Please help me out in resolving the same.

**Comment by Deluvio** [comment]
@quill-bot how was it solved?
